framework/hybrid/helm/installguide.md
Micro8s may not be available directly in an open command prompt.
Needs to be reloaded/restarted first.
=> docs: add note on `micro8s` availability

framework/hybrid/helm/installguide.md
Remove leftover `<pre><code>` syntax in favor of Markdown code syntax.
=> docs: remove leftover `<pre><code>`

framework/hybrid/helm/installguide.md
Fixes the links to sub-requisites pages.
Missed the root `.` otherwise, it lead to non-existing pages.
=> fix: prerequisites links

framework/hybrid/helm/installguide.md
Make sure that the `connectk8s` is installed, and that we use a recent version of `az`.
=> chore: add `connectedk8s` installation note

framework/hybrid/helm/prerequisites/installguide-windows.md
Inform PowerShell users to use `~` instead to navigate to the user profile folder.
Closes #162
=> chore: inform on powershell alternative

dashboard/foldersflows.md
The current Dashboard uses case sensitive flow names to determine existing flows or finding a flow by its path.
=> fix: flow name is case sensitive

dashboard/role-management.md
* Uses a Markdown table to show the different roles instead of a screenshot; this for better maintainability and rendering.
* Combine certain functionality into simpler wording.
* Use color scheme and orderning for easier navigation. 🔴🟡🟢
* Remove the `System admin` role from the folder-specific roles to not complicate things.
=> docs: propose alternative role management structure

dashboard/groupmanagement.md
The roles for the folders are already explained on a dedicated page; no need to duplicate it.
=> docs: remove duplicate role descriptions in group management

dashboard/role-management.md
Only when `Non admin` users have permissions granted will they be able to access the flow data.
=> docs: use 🟡 for non-admin users that access flow data

_sidebar.md
Refine sidebar structure to differentiate between Deprecated and Active framework components
Also removed the 'V2' naming from the active components, as they are now considered the standard.
=> Refine sidebar structure to differentiate between Deprecated and Actve components

.github/CODEOWNERS
Only @GoutsmitSam is Code Owner of Invictus and should have end-decision-rights on anything directly made public.
=> chore: Update CODEOWNERS with Sam-only rights

_sidebar.md
The ways to 'import flows' into the dashboard was 'hidden' under **Related documentation**. While this is a fundamental part of setting up the dashboard correctly.
This PR moves this to a sub-section of the **Flows** in the sidebar. Making it more clear that it all talks about the same thing.
=> docs(flow): move diagnostic settings pages to import flow sidebar item

framework/logicappsdiagnostics.md
Simplifies and re-focus the Logic Apps enable diagnostic settings page on what's important:
* `AllMetrics` should not be enabled;
* `WorkflowRuntime` should be enabled;
* `EventHubsName(space)` should point to Invictus EventHubs resource.
Adding a full sample, with already a Logic App embedded both forces us to regularly maintain the deployment. The sample has been reduced to using AVM (recommended by the Practice instead of ARM) and only showing the necessary changes to new/existing deployment templates.
=> docs(la.diagnostic): use microsoft docs + bicep avm

framework/logicappsdiagnostics.md
Make sure that we show where each diagnostic trace should be send to which EventHubs resource for types of Logic Apps.
=> docs(la.diagnostic-settings): split between consumption/standard logic apps evhb

framework/framework.md
Framework page was missing a direct link to the Exception Handler component; now added
=> Add link to Exception Handler

framework/datafactorydiagnostics.md
Streamline contents for the activation of diagnostic settings for the Azure DataFactory resource by:
* including Invictus' EventHubs resource names,
* simplify/streamline with how the LogicApps diagnostic settings are explained,
* use Bicep instead of ARM as a sample.
=> docs(df): use bicep, invictus eh & streamline w/ la in df diagnostic settings

_sidebar.md
Streamlines the 'import flow traces' for DataFactory with the other items in the sidebar, for a more user-friendly/visual-attractive sidebar.
=> docs(flow.df): streamline import flows sidebar item for data-factory

dashboard/azureADSetup.md, framework/components/deprecated/pubsub.md
When migrating possibly to Docusaurus, it fails on creating Markdown links on the following. This PR fixes these with an empty HTML `<a href="/">...</a>` instead.
=> fix(md): use empty a href io incomplete markdown link

framework/components/regextranslation.md, framework/components/timesequencer.md, framework/components/transcoV2-Example.md, framework/components/transcoV2-Matrix.md, framework/components/transcoV2.md, framework/components/xmljsonconverter.md
Several Framework components used none or incomplete Markdown code style. This PR adds the missing styles so that we also also have (later) clear syntactic coloring + correct Markdown>HTML conversion when considering Docusaurs.
=> fix(md.code): add/correct markdown code style for framework component

_sidebar.md
To continue simplifying the sidebar, we can incorporate the 'Framework overview' into the currently unused 'Framework components', making it much easier to navigate/grasp the navigation.
=> chore(fsidebar): incorporate framework overview into components title

dashboard/role-management.md
To streamline the recent changes on 'flow traces' (instead of 'flow data', as this is a technical name that was used for the `FlowData` model in Cosmos, but has no added-value). Furthermore, this PR also lets the focus on 'flows' instead of 'folders' as from a user-perspective, you want to grant permissions to flows, not folders, per se.
=> chore(role): improve language description on flows in role management

dashboard/installation/dashboard-buildpipeline.md, dashboard/installation/dashboard-releasepipeline.md, dashboard/installation/dashboard-vnet.md, framework/installation/framework-buildpipeline.md, framework/installation/framework-releasepipeline.md, framework/installation/framework-vnet.md
Docusaurus fails on things like: {prefix} as it assumes they are variables. Also for readability, we should mark them as 'code' in Markdown: `{prefix}`.
This PR does this for all dashboard/framework installation feature docs.
=> chore(installation): mark parameterized/customization in installation docs as code lang

framework/components/transcoV2-Example.md, framework/components/transcoV2-Matrix.md, framework/deprecated/matrix-basic.md, framework/deprecated/matrix-promote.md, framework/deprecated/matrix.md, framework/deprecated/pubsub.md, framework/deprecated/transco-assemblies.md, framework/deprecated/transco-extraction.md, framework/deprecated/transco.md, src/css/custom.css
Prepare to hide any sub-pages from the auto-generated Docusaurus sidebar, these pages are still URL-accessible, only not helpful to blow up the sidebar.
=> chore(docusaurus): prepare to hide subpages from docusaurus auto-gen sidebar

dashboard/installation/dashboard-buildpipeline.md
Remove direct folder reference on dashboard installation page as this is not supported by Docusaurus - and is also an unnecessary Markdown link as further down, the necessary file is linked, still.
=> chore(pipelines): remove direct /pipelines folder ref link in dashboard

versioned_docs/version-v6.0.0/dashboard/_category_.yml
Makes the `Dashboard` sidebar item by default collasible + collapsed, so that people can choose which part of the Invictus documentation site they want to navigate to, without us forcing them in a direction (Dashboard or Framework).
Closes #348
=> chore(sidebar): make dashboard sidebar item collabsible

versioned_docs/version-v6.0.0/framework/installation/pipelines/framework.build.yaml, versioned_docs/version-v6.0.0/framework/installation/pipelines/framework.release.yaml
The Framework pipeline templates used an incorrect reference to a sub-build steps YAML template. This PR fixes these references.
Closes #357
=> fix(framework): use correct sub-references in pipeline templates

versioned_docs/version-v6.0.0/dashboard/installation/pipelines/dashboard.release.yaml, versioned_docs/version-v6.0.0/framework/installation/pipelines/framework.release.yaml
The feature documentation talks about `{prefix}.invictus.*` variable groups and ACR credentials being in the `{prefix}.invictus.installation` variable groups - which aren't always correctly defined in the provided YAML templates.
This PR fixes that.
Closes #358
=> fix(var.group): correct naming convention in dashboard/framework variable groups

versioned_docs/version-v6.0.0/dashboard/flows/01_add.md, versioned_docs/version-v6.0.0/framework/deprecated/matrix.md, versioned_docs/version-v6.0.0/framework/deprecated/pubsub.md, versioned_docs/version-v6.0.0/framework/deprecated/transco.md
Some pages still mentioned 'ARM templates' while we already have moved towards Bicep a long time ago. This PR makes sure that we use 'Bicep' now.
=> chore(bicep): use bicep instead of arm mentionings throughout

versioned_docs/version-v6.0.0/support/v6-migration.md
Migrating to v6 requires a lot of changes/steps. This PR tries to make these steps more visually attractive and easier to follow by placing separate actions in `<details/>` tags.
=> chore(v6): use `<details/>` for visually attractive v6 migration guide

versioned_docs/version-v6.0.0/dashboard/installation/dashboard-migration.md, versioned_docs/version-v6.0.0/dashboard/installation/dashboard-vnet.md, versioned_docs/version-v6.0.0/dashboard/installation/index.md, versioned_docs/version-v6.0.0/framework/installation/framework-buildpipeline.md, versioned_docs/version-v6.0.0/framework/installation/framework-migration.md, versioned_docs/version-v6.0.0/framework/installation/index.md
The PR #354 made sure that the release pipelines are more descriptive, but failed to rename all link references to it. It seems that this renaming did not let the CI pipeline fail, but it did fail the CD pipeline.
This PR follows-up this file renaming, which fixes the Docusaurus CD build.
=> fix(release.pipeline): broken links on renamed .mdx release pipelines

versioned_docs/version-v6.0.0/dashboard/installation/01_give_ad_access.md
Updated documentation to specify that the scope must be named `access_as_user`, ensuring correct naming during configuration.
If the name is different the dashboard will give this error:
> The application 'xxxx' asked for scope 'access_as_user' that doesn't exist.
=> docs(entra): Clarify scope naming in documentation

src/css/custom.css, versioned_docs/version-v6.0.0/dashboard/flows/01_add.mdx
Use the correct link in the breakcrumb for the Invictus logo, as this was not correctly rendered remotely.
=> fix(breadcrumb): use md logo link in breadcrumb

versioned_docs/version-v6.0.0/dashboard/flows/04_import-flow-traces/import-flows-via-la.mdx
There are several steps that consumers need to follow for them to successfully import their flow traces into the Dashboard. The non-numbered sections were not that clear that this is part of a broader walkthrough.
This PR separates the 'importing' from the 'usage' section, by making sure that we provide a walkthrough for the 'importing' and leaving the 'usage' section directly visible.
=> chore(flowtrace.la): use walkthrough for import flow traces via la

.github/workflows/deploy-gh-pages.yml
Remove `/docs-ifa` from `baseUrl:` in the Docusaurus config when deploying from the main branch.
This fixes the recent change on the URL redirection.
=> fix(deploy): remove '/docs-ifa' route from base URL

static/CNAME
Because GitHub Pages uses a custom domain, this domain needs to be configured via a CNAME on the Docusaurus as well. To do that, one needs a CNAME file in the `/static` folder, as this gets copied to the root of the site upon deployment. This PR adds that file; without it, the GitHub Pages deployment still points to the old URL and results in 404 NotFound when accessing the custom domain.
=> fix(deploy): add missing 'CNAME' file due to redirect

versioned_docs/version-v6.0.0/dashboard/installation/index.mdx, versioned_docs/version-v6.0.0/framework/installation/index.mdx
Warn end-users for the use of non-zero `scaleMinReplicas` as this can drive the costs up, if older replicas are not disposed of in time.
Relates to https://dev.azure.com/codit/Invictus/_git/dashboard/pullrequest/9433
=> chore(scaling): warn for non-zero scale min replicas
