- architecture/architecture-diagram.md
Provide better formatting for Architecture overview
> Provide better formatting for Architecture overview

- dashboard/installation/dashboard-releasepipeline.md
New function app was added, name can be overridden but is not documented.
> Add DataFactoryReceiver parameter to dashboard-releasepipeline.md

- dashboard/installation/dashboard-releasepipeline.md
Added missing parameter in installation docs #126
> Added missing param to docs

- framework/hybrid/helm/installguide.md
> chore: use markdown code syntax

- framework/hybrid/helm/installguide.md
Add introduction section on the purpose and promise of the installation guide.
> docs: add introduction section

- framework/hybrid/helm/installguide.md
- framework/hybrid/helm/prerequisites/installguide-linux.md
- framework/hybrid/helm/prerequisites/installguide-windows.md
Separate prerequisites installation.
> docs: sep prerequisites install

- framework/hybrid/helm/installguide.md
- framework/hybrid/helm/prerequisites/installguide-linux.md
- framework/hybrid/helm/prerequisites/installguide-windows.md
Move OS-based configuration to separate installation.
> docs: move configuration to separate installation

- framework/hybrid/helm/installguide.md
Describe the Helm deploy parameters with a bit more explanation.
> docs: describe helm deploy parameters

- framework/hybrid/helm/installguide.md
Split into section alternative/optional settings.
> docs: reuse alternative settings

- framework/hybrid/helm/installguide.md
Some more background info on the purpose and end-goal of the installation guide. (Just proposal).
> docs: more descriptive intro and deploy description

- framework/components/timesequencer.md
Fix typo in time sequencer feature docs.
> fix: typo in time sequencer feature docs

- dashboard/installation/dashboard-buildpipeline.md
- dashboard/installation/dashboard-migration.md
- dashboard/installation/dashboard-releasepipeline.md
Fix the raw file paths in the feature docs pages.
Closes #174
> fix: yaml pipeline references in feature docs pages

- dashboard/groupmanagement.md
add description to sync groups process
> Improved Syns Groups documentation

- dashboard/accesscontrolrights.md
Added documentation around the `Website Contributor` role assignment and Logic App Standard and made some other updates (ARM to Bicep)
> docs: update role assignment docs

- framework/components/exceptionHandler.md
add `"SiteName": null` to body of consumption request
> docs: add `"SiteName": null` to body of consumption request

- framework/components/matrix-basic.md
- framework/components/matrix-promote.md
- framework/components/matrix.md
- framework/components/pubsub.md
- framework/components/transco-assemblies.md
- framework/components/transco-extraction.md
- framework/components/transco.md
Adds remaining deprecation warnings messages to the v1 framework components.
> docs: add deprecation messages to v1 framework components

- framework/framework.md
Reference, recommended v2 components in Framework index page.
> docs: reference always v2 components

- architecture/architecture-diagram.md
- dashboard/dashboard.md
- dashboard/foldermanagement.md
- dashboard/forgotpassword.md
- dashboard/installation/dashboard-installation.md
- dashboard/installation/dashboard-migration.md
- dashboard/installation/dashboard-releasepipeline.md
- dashboard/role-management.md
- dashboard/search.md
- dashboard/settings.md
- dashboard/support/faq.md
- framework/components/timesequencer.md
- framework/framework.md
- framework/installation/framework-buildpipeline.md
- framework/installation/framework-installation.md
- framework/installation/framework-migration.md
- framework/installation/framework-releasepipeline.md
Docusaurus automatically provides a breadcrumb for pages, so we don't need to manually maintain this throughout our documentation. This PR removes those breadcrumbs.
> chore(breadcrumb): remove unnecessary breadcrumb throughout

- versioned_docs/version-v6.0.0/framework/transcoV2.mdx
Adds the related Bicep parameters for the **Transco v2** Framework component.
> chore(transco.v2): add related bicep params for transco v2 component

- versioned_docs/version-v6.0.0/dashboard/installation/index.mdx
- versioned_docs/version-v6.0.0/framework/installation/index.mdx
- versioned_docs/version-v6.0.0/scripts/Invictus-RemoveOldRevisions.ps1
- versioned_docs/version-v6.0.0/support/v6-migration.md
Provide a clean-up script to remove old Azure Container App revisions in of Multiple Revisions mode.
Closes #460
> feat(scaling): add clean-up script for old container app revisions instalation
